package be.kdg.sa.backend.infrastructure.db.repositories.driverRepository;

import be.kdg.sa.backend.domain.Address;
import be.kdg.sa.backend.domain.delivery.OrderId;
import be.kdg.sa.backend.domain.driver.Driver;
import be.kdg.sa.backend.domain.driver.DriverId;
import be.kdg.sa.backend.infrastructure.db.repositories.EntityNotFoundException;
import be.kdg.sa.backend.infrastructure.db.repositories.driverRepository.jpa.JpaDriverEntity;
import be.kdg.sa.backend.infrastructure.db.repositories.driverRepository.jpa.JpaDriverRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class DbDriverTest {

    @Mock
    private JpaDriverRepository jpaDriverRepository;

    private DbDriver dbDriver;

    private DriverId driverId;
    private Driver driver;
    private JpaDriverEntity jpaDriverEntity;
    private OrderId activeDeliveryId;

    @BeforeEach
    void setUp() {
        dbDriver = new DbDriver(jpaDriverRepository);

        driverId = new DriverId(UUID.randomUUID());
        Address address = new Address("Main St", "123", "A", "1000", "Brussels", "BE");
        activeDeliveryId = new OrderId(UUID.randomUUID());

        driver = new Driver(driverId, "John Doe", "john@example.com",
                "+3212345678", "BE123456789", address, activeDeliveryId);

        jpaDriverEntity = JpaDriverEntity.fromDomain(driver);
    }

    @Test
    void save_ShouldConvertDomainToEntityAndSave() {
        // Arrange
        ArgumentCaptor<JpaDriverEntity> entityCaptor = ArgumentCaptor.forClass(JpaDriverEntity.class);

        // Act
        dbDriver.save(driver);

        // Assert
        verify(jpaDriverRepository).save(entityCaptor.capture());
        JpaDriverEntity capturedEntity = entityCaptor.getValue();

        assertEquals(driverId.id(), capturedEntity.getId());
        assertEquals("John Doe", capturedEntity.getName());
        assertEquals("john@example.com", capturedEntity.getEmail());
        assertEquals("+3212345678", capturedEntity.getPhoneNumber());
        assertEquals("BE123456789", capturedEntity.getAccountNumber());
        assertNotNull(capturedEntity.getAddress());
        assertEquals(activeDeliveryId.id(), capturedEntity.getActiveDeliveryId());
    }

    @Test
    void save_WithDriverWithoutAddressAndActiveDelivery_ShouldWork() {
        // Arrange
        Driver minimalDriver = new Driver(driverId, "John Doe", "john@example.com",
                "+3212345678", "BE123456789");
        ArgumentCaptor<JpaDriverEntity> entityCaptor = ArgumentCaptor.forClass(JpaDriverEntity.class);

        // Act
        dbDriver.save(minimalDriver);

        // Assert
        verify(jpaDriverRepository).save(entityCaptor.capture());
        JpaDriverEntity capturedEntity = entityCaptor.getValue();

        assertEquals(driverId.id(), capturedEntity.getId());
        assertEquals("John Doe", capturedEntity.getName());
        assertNull(capturedEntity.getAddress());
        assertNull(capturedEntity.getActiveDeliveryId());
    }

    @Test
    void save_WithNullDriver_ShouldThrowException() {
        // Act & Assert
        assertThrows(IllegalArgumentException.class, () -> dbDriver.save(null));
    }

    @Test
    void save_WithDriverWithoutId_ShouldGenerateNewId() {
        // Arrange
        Driver driverWithoutId = new Driver(null, "John Doe", "john@example.com",
                "+3212345678", "BE123456789");
        ArgumentCaptor<JpaDriverEntity> entityCaptor = ArgumentCaptor.forClass(JpaDriverEntity.class);

        // Act
        dbDriver.save(driverWithoutId);

        // Assert
        verify(jpaDriverRepository).save(entityCaptor.capture());
        JpaDriverEntity capturedEntity = entityCaptor.getValue();

        assertNotNull(capturedEntity.getId());
        // The ID should be auto-generated by JpaDriverEntity.fromDomain when driver ID is null
    }

    @Test
    void findById_WithExistingDriver_ShouldReturnDriver() {
        // Arrange
        when(jpaDriverRepository.findById(driverId.id())).thenReturn(Optional.of(jpaDriverEntity));

        // Act
        Driver result = dbDriver.findById(driverId);

        // Assert
        assertNotNull(result);
        assertEquals(driverId, result.getId());
        assertEquals("John Doe", result.getName());
        assertEquals("john@example.com", result.getEmail());
        assertEquals("+3212345678", result.getPhoneNumber());
        assertEquals("BE123456789", result.getAccountNumber());
        assertNotNull(result.getAddress());
        assertNotNull(result.getActiveDeliveryId());

        verify(jpaDriverRepository).findById(driverId.id());
    }

    @Test
    void findById_WithNonExistingDriver_ShouldThrowEntityNotFoundException() {
        // Arrange
        when(jpaDriverRepository.findById(driverId.id())).thenReturn(Optional.empty());

        // Act & Assert
        EntityNotFoundException exception = assertThrows(EntityNotFoundException.class,
                () -> dbDriver.findById(driverId));

        assertEquals("Entity not found: Driver not found: " + driverId.id(), exception.getMessage());
        verify(jpaDriverRepository).findById(driverId.id());
    }

    @Test
    void findById_WithNullDriverId_ShouldThrowException() {
        // Act & Assert
        assertThrows(NullPointerException.class, () -> dbDriver.findById(null));
    }

    @Test
    void findById_WithMinimumUUID_ShouldWork() {
        // Arrange
        DriverId minDriverId = new DriverId(new UUID(0L, 0L));
        JpaDriverEntity minEntity = JpaDriverEntity.fromDomain(
                new Driver(minDriverId, "Min Driver", "min@example.com", "+3211111111", "BE111111111")
        );
        when(jpaDriverRepository.findById(minDriverId.id())).thenReturn(Optional.of(minEntity));

        // Act
        Driver result = dbDriver.findById(minDriverId);

        // Assert
        assertNotNull(result);
        verify(jpaDriverRepository).findById(minDriverId.id());
    }

    @Test
    void findById_WithMaximumUUID_ShouldWork() {
        // Arrange
        DriverId maxDriverId = new DriverId(new UUID(-1L, -1L));
        JpaDriverEntity maxEntity = JpaDriverEntity.fromDomain(
                new Driver(maxDriverId, "Max Driver", "max@example.com", "+3299999999", "BE999999999")
        );
        when(jpaDriverRepository.findById(maxDriverId.id())).thenReturn(Optional.of(maxEntity));

        // Act
        Driver result = dbDriver.findById(maxDriverId);

        // Assert
        assertNotNull(result);
        verify(jpaDriverRepository).findById(maxDriverId.id());
    }

    @Test
    void constructor_WithNullJpaDriverRepository_ShouldThrowException() {
        // Act & Assert
        assertThrows(NullPointerException.class, () -> new DbDriver(null));
    }

    @Test
    void save_ShouldHandleEntityWithNullFieldsCorrectly() {
        // Arrange
        Driver driverWithNulls = new Driver(driverId, "John Doe", null, null, null, null, null);
        ArgumentCaptor<JpaDriverEntity> entityCaptor = ArgumentCaptor.forClass(JpaDriverEntity.class);

        // Act
        dbDriver.save(driverWithNulls);

        // Assert
        verify(jpaDriverRepository).save(entityCaptor.capture());
        JpaDriverEntity capturedEntity = entityCaptor.getValue();

        assertEquals(driverId.id(), capturedEntity.getId());
        assertEquals("John Doe", capturedEntity.getName());
        assertNull(capturedEntity.getEmail());
        assertNull(capturedEntity.getPhoneNumber());
        assertNull(capturedEntity.getAccountNumber());
        assertNull(capturedEntity.getAddress());
        assertNull(capturedEntity.getActiveDeliveryId());
    }

    @Test
    void findById_WithEntityHavingNullFields_ShouldReturnDriverWithNullFields() {
        // Arrange
        JpaDriverEntity entityWithNulls = new JpaDriverEntity(
                driverId.id(), "John Doe", null, null, null, null, null
        );
        when(jpaDriverRepository.findById(driverId.id())).thenReturn(Optional.of(entityWithNulls));

        // Act
        Driver result = dbDriver.findById(driverId);

        // Assert
        assertNotNull(result);
        assertEquals(driverId, result.getId());
        assertEquals("John Doe", result.getName());
        assertNull(result.getEmail());
        assertNull(result.getPhoneNumber());
        assertNull(result.getAccountNumber());
        assertNull(result.getAddress());
        assertNull(result.getActiveDeliveryId());
    }

    @Test
    void multipleOperations_ShouldWorkCorrectly() {
        // Arrange
        DriverId driverId1 = new DriverId(UUID.randomUUID());
        DriverId driverId2 = new DriverId(UUID.randomUUID());

        Driver driver1 = new Driver(driverId1, "Driver 1", "driver1@example.com",
                "+3211111111", "BE111111111");
        Driver driver2 = new Driver(driverId2, "Driver 2", "driver2@example.com",
                "+3222222222", "BE222222222");

        JpaDriverEntity entity1 = JpaDriverEntity.fromDomain(driver1);
        JpaDriverEntity entity2 = JpaDriverEntity.fromDomain(driver2);

        when(jpaDriverRepository.findById(driverId1.id())).thenReturn(Optional.of(entity1));
        when(jpaDriverRepository.findById(driverId2.id())).thenReturn(Optional.of(entity2));

        // Act
        dbDriver.save(driver1);
        dbDriver.save(driver2);

        Driver found1 = dbDriver.findById(driverId1);
        Driver found2 = dbDriver.findById(driverId2);

        // Assert
        assertNotNull(found1);
        assertNotNull(found2);
        assertEquals("Driver 1", found1.getName());
        assertEquals("Driver 2", found2.getName());

        verify(jpaDriverRepository, times(2)).save(any(JpaDriverEntity.class));
        verify(jpaDriverRepository).findById(driverId1.id());
        verify(jpaDriverRepository).findById(driverId2.id());
    }

    @Test
    void save_WithDriverHavingAddress_ShouldConvertAddressCorrectly() {
        // Arrange
        Address address = new Address("Main St", "123", "A", "1000", "Brussels", "BE");
        Driver driverWithAddress = new Driver(driverId, "John Doe", "john@example.com",
                "+3212345678", "BE123456789", address, null);
        ArgumentCaptor<JpaDriverEntity> entityCaptor = ArgumentCaptor.forClass(JpaDriverEntity.class);

        // Act
        dbDriver.save(driverWithAddress);

        // Assert
        verify(jpaDriverRepository).save(entityCaptor.capture());
        JpaDriverEntity capturedEntity = entityCaptor.getValue();

        assertNotNull(capturedEntity.getAddress());
        assertEquals("Main St", capturedEntity.getAddress().getStreet());
        assertEquals("123", capturedEntity.getAddress().getHouseNumber());
        assertEquals("A", capturedEntity.getAddress().getBusNumber());
        assertEquals("1000", capturedEntity.getAddress().getPostalCode());
        assertEquals("Brussels", capturedEntity.getAddress().getCity());
        assertEquals("BE", capturedEntity.getAddress().getCountry());
    }

    @Test
    void findById_WithEntityHavingAddress_ShouldConvertAddressCorrectly() {
        // Arrange
        // Assuming JpaAddressEntity has proper fromDomain/toDomain methods
        JpaDriverEntity entityWithAddress = JpaDriverEntity.fromDomain(driver);
        when(jpaDriverRepository.findById(driverId.id())).thenReturn(Optional.of(entityWithAddress));

        // Act
        Driver result = dbDriver.findById(driverId);

        // Assert
        assertNotNull(result.getAddress());
        assertEquals("Main St", result.getAddress().street());
        assertEquals("123", result.getAddress().houseNumber());
        assertEquals("A", result.getAddress().busNumber());
        assertEquals("1000", result.getAddress().postalCode());
        assertEquals("Brussels", result.getAddress().city());
        assertEquals("BE", result.getAddress().country());
    }
}